CONTRIBUTING.md, README.md
Also adds CONTRIBUTING.md which explains how to contribute to the project
=> docs(support): adds more examples and explanations in README

packages/casl-vue/.babelrc, packages/casl-vue/index.js, packages/casl-vue/package-lock.json, packages/casl-vue/package.json, packages/casl-vue/spec/config.js, packages/casl-vue/spec/plugin.spec.js, packages/casl-vue/src/index.js, packages/casl-vue/src/plugin.js
=> feat(integration): adds new folder for vue integration

packages/casl-react/package.json, packages/casl-react/src/Can.js, packages/casl-react/src/index.js
=> feat(integration): Create package for React

packages/casl-aurelia/package.json, packages/casl-aurelia/src/index.js, packages/casl-aurelia/src/value-converter.js
=> feat(integration): Create package for Aurelia

packages/casl-angular/package.json, packages/casl-angular/src/can.js, packages/casl-angular/src/index.js
=> feat(integration): Create package for Angular

packages/casl-vue/README.md
- added some articles, apostrophes and some other parts of speech
=> Some grammatical updates.

packages/casl-ability/spec/.eslintrc, packages/casl-ability/spec/ability.spec.js, packages/casl-ability/src/rule.js
=> feat(ability): adds support for field patterns in rules

.codeclimate.yml, packages/casl-ability/index.d.ts, packages/casl-ability/spec/ability.spec.js, packages/casl-ability/spec/error.spec.js, packages/casl-ability/src/ability.js, packages/casl-ability/src/error.js
=> feat(ability): adds possibility to specify custom error messages

packages/casl-ability/CHANGELOG.md
defineAbilityAbility -> defineAbility
=> DOCS: typo

docs-src/src/content/pages/package/casl-react/en.md, packages/casl-react/README.md, packages/casl-react/package-lock.json, packages/casl-react/package.json, packages/casl-react/spec/useAbility.spec.js, packages/casl-react/src/hooks/index.ts, packages/casl-react/src/hooks/useAbility.ts, packages/casl-react/src/index.ts
=> feat(react): adds useAbility hook

README.md
Improve code example provided in README.md file
=> Fix code example in README.md file

README.md
=> Fixes documentation example

packages/casl-prisma/spec/prismaQuery.spec.ts, packages/casl-prisma/src/prisma/PrismaQueryParser.ts
=> fix(prisma): fix 'isNot' and 'none' condition

packages/casl-mongoose/package.json, packages/casl-mongoose/spec/accessible_records.spec.ts, packages/casl-mongoose/src/accessible_records.ts, pnpm-lock.yaml
Update dependency mongoose to v6 and use mongoose-v6 QueryWithHelpers interface instead of DocumentQuery interface which is not present anymore.
=> update mongoose to v6 and use mongoose-v6 QueryWithHelpers interface

packages/casl-ability/spec/rulesToAST.spec.js, packages/casl-ability/src/extra.ts
Hi @stalniy,
I'm really sorry for the situation in Ukraine, I hope this stupid war can end as soon as possible.
Obviously I don't expect that you look at this PR before the end of this situation.
Thank you!
=> fix(ability): negates inverted rules in ruleToAST

packages/casl-react/README.md
=> Improve explanation of useAbility within hooks dependencies

packages/casl-angular/jest.config.js, packages/casl-angular/package.json, pnpm-lock.yaml
resolves #834 
closes #815, #832, #750 (partially)
Update done according to the Angular update guide: https://update.angular.io/?v=16.0-17.0
=> Update to Angular 17

packages/casl-ability/extra/package.json
=> fix: fixes path to extra submodule in package.json

packages/casl-mongoose/src/accessibleBy.ts
=> fix: gets rid of dist imported types which cannot be resolved at runtime

.github/workflows/release.yml, packages/casl-mongoose/src/index.ts, packages/dx/bin/release-packages.sh
=> fix: removes redundant comment
