packages/casl-ability/index.d.ts
packages/casl-ability/spec/ability.spec.js
packages/casl-ability/spec/builder.spec.js
packages/casl-ability/src/ability.js
packages/casl-ability/src/builder.js
packages/casl-ability/src/utils.js

By reusing the subjectName option passed to the Ability, we can
determine the name of the Type when it is passed into the can/cannot
method on the AbilityBuilder. This gives a nice symmetry with the
Ability checking API.
Pull Request for #58

Allow AbilityBuilder to accept the subject's Type

---

packages/casl-vue/index.d.ts

This fix a typescript error when following the tutorial:
Code:
```ts
import { abilitiesPlugin } from '@casl/vue'
import Vue from 'vue';
import ability from './ability'
new Vue({
router,
store,
ability,
render: (h) => h(App),
}).$mount('#app')
```
Error:
```
[ts]
Argument of type '{ router: VueRouter; store: Store<{}>; ability: Ability; render: (h: CreateElement) => VNode; }' is not assignable to parameter of type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Rec...'.
Object literal may only specify known properties, and 'ability' does not exist in type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Rec...'.
```

Extends ComponentOptions with `ability` member

---

packages/casl-react/src/factory.js

This Pull Request fixes React's contextual can not respecting 'not' prop.

fix react contextual can dont respect 'not' prop

---

packages/casl-ability/README.md

The two first examples were not working because of typos.

docs(ability): fix examples

---

README.md
docs/_posts/2017-07-20-define-abilities.md
packages/casl-ability/spec/ability.spec.js

I was really thrilled to find this [StackOverflow answer](https://stackoverflow.com/questions/51713053/elemmatch-support-or-alternative/51865336#51865336), so I thought it would be helpful to document it!

docs(ability): document $elemMatch support

---

packages/casl-vue/src/plugin.js

Fixes #184.
I ran the tests with vue-2.6.10 and vue-2.5.22 successfully.

perf(vue): use vue.observable if available

---

packages/casl-ability/spec/query.spec.js
packages/casl-ability/src/extra.js

Now such ability will return a query object instead of null:
```js
cannot('read', 'Post')
can('read', 'Post')
```
Also simplified code.

feat(extra): improve rulesToQuery

---

docs/_posts/2017-07-20-define-abilities.md
packages/casl-ability/spec/ability.spec.js

Following the docs, I was setting up conditions with `$regexp`, however,  that was throwing ugly errors and causing my seeder to fail.
```
Error: Unknown operation $regexp
at parse (/projectRoot/node_modules/@casl/ability/node_modules/sift/lib/index.js:499:15)
at parse (/projectRoot/node_modules/@casl/ability/node_modules/sift/lib/index.js:501:61)
at createRootValidator (/projectRoot/node_modules/@casl/ability/node_modules/sift/lib/index.js:512:19)
at sift (/projectRoot/node_modules/@casl/ability/node_modules/sift/lib/index.js:534:19)
at new e (/projectRoot/node_modules/@casl/ability/dist/umd/index.js:1:1282)
at e.t.buildIndexFor (/projectRoot/node_modules/@casl/ability/dist/umd/index.js:1:2698)
at e.t.update (/projectRoot/node_modules/@casl/ability/dist/umd/index.js:1:2497)
at new e …
```

Fix erroneous references to mongoDB `$regexp`

---

packages/casl-mongoose/package.json
packages/casl-mongoose/spec/accessible_records.spec.js
packages/casl-mongoose/src/accessible_records.js

Fixes https://github.com/stalniy/casl/issues/272
In order to test I needed to check the "private" attribute `_conditions` on the query. This probably isn't preferable but I wasn't able to think of another way. If you happen to know of one I'll gladly make the change

Fixed `$and` condition being overridden on queries

---

README.md

Casl Mongoose link on readme.md was redirecting to Vue instead of Mongoose

Fixes Casl Mongoose link

---

packages/casl-vue/README.md

It currently imports from @casl/angular instead of @casl/ability

Fixed import sample on TS support section

---

docs-src/src/content/pages/guide/subject-type-detection/en.md

Added checking for `__typename` as that could potentially be a falsy value.

docs: Adjusted subjectTypeFromGraphql example

---

docs-src/src/content/pages/cookbook/roles-with-static-permissions/en.md

Changed the imported function `updateUser` to `updateUserById` which actually exists in the users service.

docs(cookbook): fixes wrong function name used in updateUserDetails

---

packages/casl-angular/README.md
packages/casl-angular/package.json
packages/casl-angular/spec/AbilityModule.e2e.spec.ts
packages/casl-angular/spec/AblePipe.spec.ts
packages/casl-angular/src/AbilityModule.ts
packages/casl-angular/src/pipes.ts
packages/casl-angular/tsconfig.json
packages/casl-angular/tsconfig.types.json
pnpm-lock.yaml

Closes #514, #512
BREAKING CHANGE: there are 2 important changes:
* deprecated CanPipe was removed, use AblePipe instead
* library is compiled by Ivy and no longer support ViewEngine

chore(deps): updates angular to v12

---

packages/casl-ability/spec/ability.spec.js
packages/casl-ability/src/RuleIndex.ts
packages/casl-ability/src/types.ts
packages/casl-ability/src/utils.ts

Fixes #527
Contains 2 minor breaking changes which should not affect anybody:
1. `createAliasResolver` validates alias map in any env now, can be changed by specifying `skipValidation`  option. Previously, it did validation in non production envs only
2. `detectSubjectType` option should not handle undefined subject anymore, as it's handled by library internally

feat(ability): adds posibility to define custom any action and any subject type instead of using `manage` and `all`

---

packages/casl-prisma/src/PrismaAbility.ts

fix: add 'all' to AbilityTuple

---

docs-src/src/components/App.js
docs-src/src/components/AppHeader.js

Hi,
The current version of the documentation which contains "Stop war in Ukraine" notification blocks the header menu items. So, I decided to fix this issue and pin the notification to the top of the header of the page.  
Examples:
<details>
<summary>Before mobile version</summary>
</details>
<details>
<summary>After mobile version</summary>
</details>
<details>
<summary>Before desktop</summary>
</details>
<details>
<summary>After desktop</summary>
</details>

Pin war notification to the header

---

packages/casl-prisma/spec/PrismaAbility.spec.ts
packages/casl-prisma/src/PrismaAbility.ts

https://github.com/stalniy/casl/pull/615 forces the user to define their AppAbility like `PrismaAbility<[string, 'all' | Subjects<{ ... }>]>`. This fix makes sure the user does not have to provide the 'all' union and can define it like `PrismaAbility<[string, Subjects<{ ... }>]>`.

fix: improved AbilityTuple

---

packages/casl-prisma/package.json
pnpm-lock.yaml

This PR updates the prisma version of the `casl-prisma` package to `^4.0.0` 
Afaik the package does not use any code parts that would fall under the [breaking changes section](https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-4#breaking-changes) of prisma's docs.
I ran all unit tests and those also seem to be fine :raised_hands: 
If you need anything else hit me up
closes https://github.com/stalniy/casl/issues/636

fix: update prisma to version 4

---

packages/casl-mongoose/package.json
packages/casl-mongoose/spec/accessible_fields.spec.ts
packages/casl-mongoose/spec/accessible_records.spec.ts
packages/casl-mongoose/src/accessible_fields.ts
packages/casl-mongoose/src/accessible_records.ts
packages/casl-mongoose/src/index.ts
packages/casl-mongoose/src/mongo.ts
pnpm-lock.yaml

* Allow to use without `extends Document` syntax
* Requires at least Mongoose 6.0.13 due to `HydratedDocument`
* See https://github.com/stalniy/casl/issues/634
Closes #634

Adapt Mongoose typings

---

packages/casl-angular/package.json
pnpm-lock.yaml

The goal of this pr is to update angular to 14 and be able to use casl with the last main version of angular
Closes #661

chore(deps): update angular monorepo to v14 (major) 

---

packages/casl-vue/src/component/can.ts

Fixes [#695](https://github.com/stalniy/casl/issues/695).
The old way of checking the presence of a prop forbade the use of `I`, `this`, `an`, and `a`.

fix: handles vue prop aliases properly

---

docs-src/src/content/pages/api/casl-ability-extra/en.md

Hi, I found a broken link in the @casl/ability/extra API

Fixed broken link in docs: missing https:// in external link

---

packages/casl-mongoose/package.json
packages/casl-mongoose/spec/accessible_records.spec.ts
pnpm-lock.yaml

I had to remove some tests since mongoose v7 has [dropped callbacks support](https://mongoosejs.com/docs/migrating_to_7.html#dropped-callback-support).

Update dependency mongoose to v7

---

packages/casl-mongoose/README.md
packages/casl-mongoose/spec/accessibleBy.spec.ts
packages/casl-mongoose/spec/mongo_query.spec.ts
packages/casl-mongoose/src/accessible_records.ts
packages/casl-mongoose/src/index.ts
packages/casl-mongoose/src/mongo.ts

**Before**
```ts
PostSchema = new Schema({})
PostSchema.plugin(accessibleRecordsPlugin)
const Post = mongoose.model<...>('Post', Post)
Post.accessibleBy(ability, 'read')
```
**After**
```ts
PostSchema = new Schema({})
const Post = mongoose.model<...>('Post', Post)
Post.find(accessibleBy(ability, 'read').Post)
```

feat: adds accessibleBy helper and deprecates `toMongoQuery` and `accessibleRecordsPlugin`

---

packages/casl-ability/src/extra.ts

Fixes https://github.com/stalniy/casl/issues/875
Backwards compatibility should be maintained because:
1. Any consumer explicitly importing and specifying `T` in `RuleToQueryConverter<T>` can continue to do so because the new generic param has a default
2. Likewise for consumers choosing to explicitly specify `T` in `rulesToQuery<T>`

Strongly type 'rulesToQuery' return based on return from 'convert' param

---

packages/casl-react/README.md

Hey team 👋 Thanks a lot for the work put on this package 👍

docs(react-README): updates links to point to /v6

---

packages/casl-ability/spec/builder.spec.js
packages/casl-ability/src/AbilityBuilder.ts

Fixes https://github.com/stalniy/casl/issues/981

Allow arrow functions for ability factory arguments to AbilityBuilder

---

packages/casl-mongoose/README.md

I almost copied the wrong code, because the example is not clearly marked as wrong code

docs: make clear that the spread operator example is a bad idea

---

packages/casl-prisma/spec/AppAbility.ts
packages/casl-prisma/src/accessibleByFactory.ts

When using the `accessibleBy` function of `casl/prisma`, the action names property is not autocompleted in Typescript although it could be inferred.
e.g. in this case `update` would not be autocompleted which could result in issues and causes a degraded DX.
```
accessibleBy(ability, 'update')
```
This PR infers the possible actions from the ability passed as the first parameter.

feat: update accessibleBy function of casl/prisma to autocomplete action names
